complete sgt-back-end challenge -- Cameron Peck
cam-peck/rc0822-code-solutions pull request #106
Opened 2022-10-21 23:54 UTC by cam-peck

https://user-images.githubusercontent.com/105157437/197306187-16fea2c1-ce42-4351-95a0-7dba29744cb6.mp4

2022-10-22 00:04 UTC, TimelikeClosure requested changes

2022-10-22 00:04 UTC, TimelikeClosure commented on sgt-back-end/index.js
> +  }
Grade Ids should also be valid integers

2022-10-22 00:25 UTC, cam-peck commented
Thanks for the feedback, Tim! Have made those fixes!

https://user-images.githubusercontent.com/105157437/197308021-87757a40-5730-410a-8a49-c3660db3e7ed.mp4

2022-10-24 15:46 UTC, TimelikeClosure approved these changes

2022-10-24 16:00 UTC, merged